### ISSUE TITLE
aws-config clashes with node-red-contrib-aws-sdk

### ISSUE THREAD

**Issue by bluepup** [node-red/node-red-web-nodes#165]
The configuration node from "node-red-web-nodes" has the same name (aws-config) as "node-red-contrib-aws-sdk". If you install both neither will work.

**Comment by knolleary** [comment]
Not much we can do about that. We can't change the type name without breaking users. Type name clashes are unfortunate and rely on developers doing some due diligence - especially for such specific nodes as aws

**Comment by knolleary** [comment]
If anything, the core runtime should try to detect such a clash. Due to the asynchronous nature of node loading, it's a non trivial task which is why it doesn't do it today.

**Comment by cuongquay** [comment]
What should I do for this :) @bluepup

**Comment by bluepup** [comment]
You might want to fix it.


Am 10.02.2017 um 17:24 schrieb Duong Dinh Cuong:

**Comment by knolleary** [comment]
@cuongquay the problem comes because you've used the same type name as the existing aws node.

This is an unfortunate position to be in - if either of us changes the type name to avoid the clash we will break existing users of the node.

As I said above, the longer term solution is for us to update the runtime to handle this better.

For now, the answer is to not install both of these nodes.

**Comment by cuongquay** [comment]
R
