### ISSUE TITLE
Dropbox needs update to v2 API

### ISSUE THREAD

**Issue by jamieshaw** [node-red/node-red-web-nodes#184]
It appears that the Dropbox node no longer functions. This is most likely due to lack of updates, and Dropbox's recent requirement for it's v2 API.

**Comment by mrummuka** [comment]
According to https://www.dropbox.com/developers/reference/migration-guide api v1 should still work but only a couple of days more ("On September 28, 2017, API v1 will be turned off, so it's time to move to API v2.").  Regardless, this should definitely be upgraded to api v2 asap.

**Comment by humoba** [comment]
Please! Update to API v2, in this moment doesn't work

**Comment by knolleary** [comment]
If anyone in the community wants to help make this change it will definitely get it done quicker...

**Comment by cellerich** [comment]
Sitting in the same boat with the broken Dropbox Node.
Would love to help with this node, but my skills are not there yet.

As a workaround for others with this problem - use the "Box" node. Has the same interface in node red and is very easy to setup.

**Comment by knolleary** [comment]
Good news everyone. I've mostly got the node updated to the new API. A couple things left to do before publishing it, but its almost done.

The bad news is that due to some of the changes in the API, I've had to alter the one of the node's behaviour slightly. The 'Dropbox In' node, that watches for changes, no longer includes `msg.data`  in the messages it emits.

Due to this, the node will be getting a major version number bump.

**Comment by knolleary** [comment]
Hi, I've just published a beta version of the updated node. Given the nature of the changes I'm looking for people to test the new version before it is published fully.

If you're willing to try it out use the following command to install in your `~/.node-red` directory:

    npm install node-red-node-dropbox@beta

Notes:

 - you _may_ need to update your access token - I didn't have an old one to test the migration fully.
 - the Dropbox In node no longer includes `msg.data` in the messages it emits
 - the Dropbox In node should emit messages much quicker - it uses the new api's polling api, rather than checking every 10 minutes.

**Comment by driveland** [comment]
Hi, Thank you for making the changes! I installed the beta version and tried out the Dropbox Out node (this is currently the only node I'm using). It worked out of the box and I didn't need to update any access token. But once a file was uploaded to Dropbox, writing the same file again does generate an error. In the Node-RED debug view the msg.payload shows "[object Object]".

**Comment by knolleary** [comment]
@driveland ah - I can see a route through the code that would cause that... I'm guessing you're using `localFilename` to identify the file to upload rather than passing the contents in under `msg.payload`. Let me know if that isn't the case, but in the meantime I'll fix that and get a 1.0.1 beta published

**Comment by knolleary** [comment]
@driveland have published 1.0.1 with a fix. Please update and let me know:

    npm install node-red-node-dropbox@beta

**Comment by driveland** [comment]
@knolleary I'm indeed using msg.localFilename to identify the file to upload. I installed version 1.0.1 and it seems to be fixed. Thanks!!!

**Comment by driveland** [comment]
@knolleary The Dropbox Out node is working fine. No issues so far. So I tried the Dropbox In node. I can confirm that it's quite fast. Each time it almost emits instantaneously upon change. In the description of this node it says that msg.payload contains "The full path of the changed file". That is however not the case. Each time msg.payload equals msg.file preceeded by a '/' character, even though the actual path is two folders deep.

**Comment by ktinkerer** [comment]
@knolleary I've just tested the dropbox out node and that worked fine which is great because that is the one I use, thank you! However I tried out the dropbox in node and it failed with `TypeError: node.trace is not a function`

**Comment by knolleary** [comment]
@ktinkerer I assume you're using an older version of Node-RED; node.trace was added in 0.17.
I will put a guard in to avoid the error, but I recommend you upgrade if you can.

**Comment by ktinkerer** [comment]
@knolleary You are right I was using 0.16.2, upgraded Node-RED to 0.17.5 and it seems to be working fine now. Thanks for your help!

**Comment by knolleary** [comment]
Now published to npm as v1.0.2

**Comment by OpaStefanVogel** [comment]
Version "beta" is working fine on Raspberry Pi with Raspbian. Thanks!!!! In folder .node-red/node_modules now a lot of files outside of folder node-red-node-dropbox.
