### ISSUE TITLE
OpenWeatherMap - Can't Define Location

### ISSUE THREAD

**Issue by stavrosdidakis** [node-red/node-red-web-nodes#211]
Hi all,

I am having this issue that I try to pass using a function so that I format a location in order to set the OpenWeatherMap node.

This is my function:

`var loc = {};
var outMsg = {};
location = msg.payload;

if (location == "Shanghai"){
    loc = {"location" : [{"city":"Shanghai"}, {"country":"China"}]};
}
if (location == "London"){
    loc = {"location" : [{"city":"London"}, {"country":"United Kingdom"}]};
}

outMsg.payload = loc;
return outMsg;`

However, I am not able to see any results coming out of the OpenWeatherMap node. I am having a difficulty finding documentation, so I would like to know how to achieve that. 

Thanks

**Comment by dceejay** [comment]
Hi - we much prefer general how-to questions via either the google mailing list or slack channel as there are many more people watching those who could help you rather than rely on the core team.

In your case the info for the node says
![image](https://user-images.githubusercontent.com/5375409/35485348-46d9cec2-0456-11e8-8ddd-7ea01d677c42.png)
but you are not setting those properties on the msg
you need something like

    
```
if (msg.payload == "Shanghai") {
  msg.location = {"city":"Shanghai", "country":"China"};
}
if (msg.payload == "London") {
  msg.location = {"city":"London", "country":"United Kingdom"};
}
return msg;

```
